# Generated by Django 3.2.4 on 2021-07-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20210705_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privillages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privillages_name', models.CharField(max_length=50)),
            ],
        ),
    ]
