# Generated by Django 3.2.4 on 2021-07-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0009_remove_usermodel1_pri'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel1',
            name='pri',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
