# Generated by Django 3.2.4 on 2021-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0010_usermodel1_pri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel1',
            name='pri',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
