# Generated by Django 3.2.4 on 2021-07-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0011_alter_usermodel1_pri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
                ('pri', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserModel1',
        ),
    ]
